"""
pr_manager.py
Creates a PR on the target repo with the verified patch,
or labels it Manual Review Required if something failed.
"""

import requests
import os
import base64
import json
from pathlib import Path


GITHUB_API = "https://api.github.com"


def _headers() -> dict:
    token = os.environ.get("GITHUB_TOKEN", "")
    return {
        "Authorization": f"Bearer {token}",
        "Accept": "application/vnd.github+json",
        "X-GitHub-Api-Version": "2022-11-28",
    }


def _get_default_branch(repo_path: str) -> str:
    resp = requests.get(f"{GITHUB_API}/repos/{repo_path}", headers=_headers())
    resp.raise_for_status()
    return resp.json().get("default_branch", "main")


def _get_file_sha(repo_path: str, file_path: str, branch: str) -> str | None:
    resp = requests.get(
        f"{GITHUB_API}/repos/{repo_path}/contents/{file_path}",
        headers=_headers(),
        params={"ref": branch},
    )
    if resp.status_code == 200:
        return resp.json().get("sha")
    return None


def create_patch_pr(
    repo_path: str,
    finding: dict,
    patch_code: str,
    signature_info: dict,
) -> dict:
    """
    Create a branch with the patched file and open a PR.
    repo_path: "owner/repo"
    finding: the finding dict from scanner (has file, line, cwe, function_name)
    patch_code: the verified patch
    signature_info: from signer.py
    """
    print(f"[pr] Creating PR on {repo_path}...")

    default_branch = _get_default_branch(repo_path)
    branch_name = f"secops/fix-{finding['cwe'].lower()}-{finding['function_name']}"

    # Read the original file
    file_path = finding["file"]
    # Make path relative to repo root
    rel_file = _make_relative(file_path)

    # Get current file content from GitHub
    content_resp = requests.get(
        f"{GITHUB_API}/repos/{repo_path}/contents/{rel_file}",
        headers=_headers(),
        params={"ref": default_branch},
    )
    content_resp.raise_for_status()
    content_data = content_resp.json()
    original_content = base64.b64decode(content_data["content"]).decode("utf-8")
    file_sha = content_data["sha"]

    # Replace the vulnerable function with the patch
    patched_content = _replace_function(
        original_content,
        finding["source_code"],
        patch_code,
    )

    # Create branch
    ref_resp = requests.get(
        f"{GITHUB_API}/repos/{repo_path}/git/ref/heads/{default_branch}",
        headers=_headers(),
    )
    ref_resp.raise_for_status()
    sha = ref_resp.json()["object"]["sha"]

    requests.post(
        f"{GITHUB_API}/repos/{repo_path}/git/refs",
        headers=_headers(),
        json={"ref": f"refs/heads/{branch_name}", "sha": sha},
    )

    # Push patched file to new branch
    requests.put(
        f"{GITHUB_API}/repos/{repo_path}/contents/{rel_file}",
        headers=_headers(),
        json={
            "message": f"fix({finding['cwe']}): auto-patch {finding['function_name']}",
            "content": base64.b64encode(patched_content.encode()).decode(),
            "sha": file_sha,
            "branch": branch_name,
        },
    )

    # Open PR
    pr_resp = requests.post(
        f"{GITHUB_API}/repos/{repo_path}/pulls",
        headers=_headers(),
        json={
            "title": f"[SecOps] Fix {finding['cwe']} in {finding['function_name']}",
            "body": _pr_body(finding, signature_info),
            "head": branch_name,
            "base": default_branch,
        },
    )
    pr_resp.raise_for_status()
    pr_url = pr_resp.json().get("html_url", "")
    print(f"[pr] ✅ PR created: {pr_url}")
    return {"pr_url": pr_url, "branch": branch_name}


def label_manual_review(repo_path: str, finding: dict, reason: str) -> None:
    """
    Open a PR (or issue) labeled Manual Review Required
    when the pipeline cannot auto-fix.
    """
    print(f"[pr] Flagging {finding['function_name']} for manual review: {reason}")

    default_branch = _get_default_branch(repo_path)

    requests.post(
        f"{GITHUB_API}/repos/{repo_path}/issues",
        headers=_headers(),
        json={
            "title": f"[SecOps] Manual Review Required — {finding['cwe']} in {finding['function_name']}",
            "body": f"""## Vulnerability Detected — Auto-remediation failed

**File:** `{finding['file']}`
**Function:** `{finding['function_name']}`
**CWE:** `{finding['cwe']}`
**Scanner:** `{finding['tool']}`
**Reason auto-patch was not applied:** {reason}

### Original finding
{finding['message']}

---
*Generated by SecOps Pipeline*
""",
            "labels": ["manual-review-required", "security"],
        },
    )


def _replace_function(original: str, old_function: str, new_function: str) -> str:
    """Replace the old function source with the patched version."""
    if old_function in original:
        return original.replace(old_function, new_function, 1)
    # fallback: append patch as comment if exact match fails
    return original + f"\n\n/* SecOps patched version:\n{new_function}\n*/"


def _make_relative(file_path: str) -> str:
    """Strip /tmp/target_repo/ prefix to get repo-relative path."""
    prefix = "/tmp/target_repo/"
    if file_path.startswith(prefix):
        return file_path[len(prefix):]
    return file_path


def _pr_body(finding: dict, signature_info: dict) -> str:
    return f"""## Automated Security Patch

| Field | Value |
|---|---|
| **CWE** | `{finding['cwe']}` |
| **File** | `{finding['file']}` |
| **Function** | `{finding['function_name']}` |
| **Scanner** | `{finding['tool']}` |
| **Digest** | `{signature_info.get('digest', 'N/A')}` |
| **Signature mode** | `{signature_info.get('mode', 'N/A')}` |

### What was found
{finding['message']}

### Verification
- ✅ Compiled successfully with ASan + UBSan
- ✅ Survived libFuzzer (100k runs)
- ✅ Cryptographically signed

---
*Generated by SecOps Pipeline — review before merging*
"""
